import type { Metadata } from "next";
import { Changa, Inter } from "next/font/google";
import "./globals.css";
import { cn } from "../lib/utils";

const changa = Changa({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={cn(changa)}>{children}</body>
    </html>
  );
}
